# Flash programmer parameters file
# Automatically generated by SDK (29/04/2011 14:43:19).

set FLASH_FILE                    "C:/User/Doctor/papers/libro_Deschamps/edk13.1/reconfig/bitstream/partial_determinant.bit"
set FLASH_BASEADDR                0xA0000000
set FLASH_PROG_OFFSET             0x00F80000
set FLASH_BUSWIDTH                8
set SCRATCH_BASEADDR              0x00000000
set SCRATCH_LEN                   0x00010000
set TARGET_TYPE                   "MICROBLAZE"
set PROC_INSTANCE                 "microblaze_0"
set EXTRA_COMPILER_FLAGS          "-mxl-barrel-shift -mno-xl-soft-mul "
set XMD_CONNECT                   "connect mb mdm  -debugdevice cpunr 1"
set ENDIANNESS                    "BE"
